export const SET_CHARACTERS = 'SET_CHARACTERS'
export const SET_CHARACTER = 'SET_CHARACTER'
export const SET_EPISODES = 'SET_EPISODES'
export const SET_PAGINATION = 'SET_PAGINATION'
export const SET_FILTER_OPTION = 'SET_FILTER_OPTION'

export const SET_ERRORS = 'SET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
